import sys
from dataclasses import dataclass

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder, StandardScaler

from source_code.exception import CustomException
from source_code.logger import logging
import os
from source_code.utils import save_function
from functools import partial  # For creating a custom transformer


@dataclass
class DataTransformationConfig:
    preprocessor_obj_file_path = os.path.join("artifacts", "preprocessor.pkl")


class DataTransformation:
    def __init__(self):
        self.data_transformation_config = DataTransformationConfig()

    def get_data_transformation_object(self):
        try:
            logging.info("Data Transformation initiated")
            # Define which columns should be ordinal-encoded and which should be scaled
            categorical_cols = ["Airline", "AirportFrom", "AirportTo", "DayOfWeek"]
            numerical_cols = ["Flight", "Time", "Length"]

            # Define the custom ranking for each ordinal variable
            airline_categories = [
                "US",
                "AA",
                "AS",
                "CO",
                "DL",
                "B6",
                "HA",
                "OO",
                "9E",
                "OH",
                "EV",
                "XE",
                "YV",
                "UA",
                "MQ",
                "FL",
                "F9",
                "WN",
            ]
            airportfrom_categories = [
                "PHX",
                "LAX",
                "SFO",
                "ANC",
                "LAS",
                "SLC",
                "DEN",
                "ONT",
                "FAI",
                "BQN",
                "PSE",
                "HNL",
                "BIS",
                "IYK",
                "EWR",
                "BOS",
                "MKE",
                "GFK",
                "OMA",
                "GSO",
                "LMT",
                "SEA",
                "MCO",
                "TPA",
                "DLH",
                "MSP",
                "FAR",
                "MFE",
                "MSY",
                "VPS",
                "BWI",
                "MAF",
                "LWS",
                "RST",
                "ALB",
                "DSM",
                "CHS",
                "MSN",
                "JAX",
                "SAT",
                "PNS",
                "BHM",
                "LIT",
                "SAV",
                "BNA",
                "ICT",
                "ECP",
                "DHN",
                "MGM",
                "CAE",
                "PWM",
                "ACV",
                "EKO",
                "PHL",
                "ATL",
                "PDX",
                "RIC",
                "BTR",
                "HRL",
                "MYR",
                "TUS",
                "SBN",
                "CAK",
                "TVC",
                "CLE",
                "ORD",
                "DAY",
                "MFR",
                "BTV",
                "TLH",
                "TYS",
                "DFW",
                "FLL",
                "AUS",
                "CHA",
                "CMH",
                "LRD",
                "BRO",
                "CRP",
                "LAN",
                "PVD",
                "FWA",
                "JFK",
                "LGA",
                "OKC",
                "PIT",
                "PBI",
                "ORF",
                "DCA",
                "AEX",
                "SYR",
                "SHV",
                "VLD",
                "BDL",
                "FAT",
                "BZN",
                "RDM",
                "LFT",
                "IPL",
                "EAU",
                "ERI",
                "BUF",
                "IAH",
                "MCI",
                "AGS",
                "ABI",
                "GRR",
                "LBB",
                "CLT",
                "LEX",
                "MBS",
                "MOD",
                "AMA",
                "SGF",
                "AZO",
                "ABE",
                "SWF",
                "BGM",
                "AVP",
                "FNT",
                "GSP",
                "ATW",
                "ITH",
                "TUL",
                "COS",
                "ELP",
                "ABQ",
                "SMF",
                "STL",
                "IAD",
                "DTW",
                "RDU",
                "RSW",
                "OAK",
                "ROC",
                "IND",
                "CVG",
                "MDW",
                "SDF",
                "ABY",
                "TRI",
                "XNA",
                "ROA",
                "MLI",
                "LYH",
                "EVV",
                "HPN",
                "FAY",
                "EWN",
                "CSG",
                "GPT",
                "MLU",
                "MOB",
                "OAJ",
                "CHO",
                "ILM",
                "BMI",
                "PHF",
                "ACY",
                "JAN",
                "CID",
                "GRK",
                "HOU",
                "CRW",
                "HTS",
                "PSC",
                "BOI",
                "SBP",
                "CLD",
                "PSP",
                "SBA",
                "MEM",
                "MRY",
                "GEG",
                "RDD",
                "PAH",
                "CMX",
                "SPI",
                "EUG",
                "CIC",
                "PIH",
                "SGU",
                "COD",
                "MIA",
                "MHT",
                "GRB",
                "FSD",
                "SJU",
                "AVL",
                "BFL",
                "RAP",
                "DRO",
                "PIA",
                "OGG",
                "SIT",
                "TXK",
                "RNO",
                "DAL",
                "SCE",
                "MEI",
                "MDT",
                "FCA",
                "SJC",
                "KOA",
                "PLN",
                "SAN",
                "GNV",
                "HLN",
                "GJT",
                "CPR",
                "FSM",
                "CMI",
                "GTF",
                "HDN",
                "ITO",
                "MTJ",
                "HSV",
                "BTM",
                "BIL",
                "COU",
                "MSO",
                "SMX",
                "TWF",
                "ISP",
                "GCC",
                "LIH",
                "LNK",
                "DAB",
                "SNA",
                "MQT",
                "LGB",
                "CWA",
                "LSE",
                "BUR",
                "ACT",
                "MHK",
                "MOT",
                "IDA",
                "SUN",
                "GTR",
                "MLB",
                "SRQ",
                "JAC",
                "ASE",
                "LCH",
                "JNU",
                "ROW",
                "BQK",
                "YUM",
                "FLG",
                "EGE",
                "GUC",
                "EYW",
                "RKS",
                "BGR",
                "ELM",
                "ADQ",
                "OTZ",
                "OTH",
                "STT",
                "KTN",
                "BET",
                "SJT",
                "CDC",
                "CEC",
                "SPS",
                "SCC",
                "STX",
                "OME",
                "MKG",
                "WRG",
                "TYR",
                "BRW",
                "GGG",
                "PSG",
                "BKG",
                "YAK",
                "CLL",
                "SAF",
                "CYS",
                "LWB",
                "CDV",
                "FLO",
                "BLI",
                "DBQ",
                "TOL",
                "UTM",
                "PIE",
                "ADK",
                "ABR",
                "TEX",
                "MMH",
                "GUM",
            ]
            airportto_categories = [
                "CLT",
                "DFW",
                "SEA",
                "IAH",
                "MSP",
                "DTW",
                "ORD",
                "ATL",
                "PDX",
                "JFK",
                "SLC",
                "HNL",
                "PHX",
                "MCO",
                "OGG",
                "LAX",
                "KOA",
                "ITO",
                "SFO",
                "MIA",
                "IAD",
                "SMF",
                "PHL",
                "LIH",
                "DEN",
                "LGA",
                "MEM",
                "CVG",
                "YUM",
                "CWA",
                "MKE",
                "BQN",
                "FAI",
                "LAS",
                "ANC",
                "BOS",
                "LGB",
                "FLL",
                "SJU",
                "EWR",
                "DCA",
                "BWI",
                "RDU",
                "MCI",
                "TYS",
                "SAN",
                "ONT",
                "OAK",
                "MDW",
                "BNA",
                "DAL",
                "CLE",
                "JAX",
                "JNU",
                "RNO",
                "ELP",
                "SAT",
                "OTZ",
                "MBS",
                "BDL",
                "STL",
                "HOU",
                "AUS",
                "SNA",
                "SJC",
                "LIT",
                "TUS",
                "TUL",
                "CMH",
                "LAN",
                "IND",
                "AMA",
                "CRP",
                "PIT",
                "RKS",
                "FWA",
                "TPA",
                "PBI",
                "JAN",
                "DSM",
                "ADQ",
                "GRB",
                "PVD",
                "ABQ",
                "SDF",
                "RSW",
                "MSY",
                "BUR",
                "BOI",
                "TLH",
                "BHM",
                "ACV",
                "ORF",
                "BET",
                "KTN",
                "RIC",
                "SRQ",
                "BTR",
                "XNA",
                "MHT",
                "GRR",
                "SBN",
                "SBA",
                "ROA",
                "CID",
                "GPT",
                "MFR",
                "SGU",
                "HPN",
                "OMA",
                "OTH",
                "GSP",
                "LMT",
                "BUF",
                "MSN",
                "BFL",
                "CAE",
                "HRL",
                "OKC",
                "SYR",
                "COS",
                "BTV",
                "CDC",
                "SCC",
                "DAY",
                "SJT",
                "TVC",
                "ROC",
                "ISP",
                "MRY",
                "SBP",
                "MLI",
                "MOB",
                "CIC",
                "SAV",
                "FAT",
                "EKO",
                "GEG",
                "ECP",
                "LFT",
                "SUN",
                "HSV",
                "SHV",
                "CHA",
                "CAK",
                "BZN",
                "MAF",
                "GSO",
                "MDT",
                "PHF",
                "ICT",
                "AZO",
                "RAP",
                "CHS",
                "CLD",
                "MKG",
                "VPS",
                "PIH",
                "ATW",
                "AGS",
                "PNS",
                "BIL",
                "SPI",
                "FAR",
                "CPR",
                "PIA",
                "SPS",
                "TWF",
                "LBB",
                "ALB",
                "CEC",
                "DRO",
                "GJT",
                "GNV",
                "RST",
                "AVL",
                "GRK",
                "PSP",
                "LEX",
                "TRI",
                "SGF",
                "FSM",
                "RDD",
                "OME",
                "MFE",
                "LSE",
                "BMI",
                "MYR",
                "FAY",
                "FSD",
                "EUG",
                "MGM",
                "EVV",
                "MLB",
                "FNT",
                "STT",
                "WRG",
                "ABE",
                "BIS",
                "MOT",
                "MLU",
                "GFK",
                "RDM",
                "COU",
                "LRD",
                "PSC",
                "MOD",
                "PWM",
                "ILM",
                "ABY",
                "CRW",
                "TXK",
                "BRO",
                "BRW",
                "EYW",
                "DAB",
                "ROW",
                "ABI",
                "EAU",
                "TYR",
                "MSO",
                "FLG",
                "CSG",
                "VLD",
                "DHN",
                "OAJ",
                "AEX",
                "CHO",
                "SAF",
                "GGG",
                "FCA",
                "ASE",
                "BKG",
                "MHK",
                "LNK",
                "MQT",
                "YAK",
                "GTR",
                "SMX",
                "SWF",
                "ITH",
                "AVP",
                "ELM",
                "BGM",
                "SIT",
                "PSG",
                "CYS",
                "CLL",
                "SCE",
                "LWB",
                "LCH",
                "GCC",
                "IYK",
                "LWS",
                "COD",
                "HLN",
                "BQK",
                "GTF",
                "DLH",
                "BTM",
                "EGE",
                "IDA",
                "JAC",
                "HDN",
                "MTJ",
                "CMX",
                "CMI",
                "CDV",
                "LYH",
                "ACT",
                "STX",
                "IPL",
                "PAH",
                "HTS",
                "MEI",
                "BLI",
                "ERI",
                "EWN",
                "FLO",
                "ACY",
                "DBQ",
                "TOL",
                "GUC",
                "PLN",
                "BGR",
                "PSE",
                "PIE",
                "UTM",
                "ADK",
                "ABR",
                "TEX",
                "MMH",
                "GUM",
            ]
            dayofweek_categories = [1, 2, 3, 4, 5, 6, 7]

            logging.info("Pipeline Initiated")

            ## Numerical Pipeline
            num_pipeline = Pipeline(
                steps=[
                    ("imputer", SimpleImputer(strategy="median")),
                    ("scaler", StandardScaler()),
                ]
            )

            # Categorigal Pipeline
            cat_pipeline = Pipeline(
                steps=[
                    ("imputer", SimpleImputer(strategy="most_frequent")),
                    (
                        "ordinalencoder",
                        OrdinalEncoder(
                            categories=[
                                airline_categories,
                                airportfrom_categories,
                                airportto_categories,
                                dayofweek_categories,
                            ]
                        ),
                    ),
                    ("scaler", StandardScaler()),
                ]
            )

            preprocessor = ColumnTransformer(
                [
                    ("num_pipeline", num_pipeline, numerical_cols),
                    ("cat_pipeline", cat_pipeline, categorical_cols),
                ]
            )
            logging.info("Pipeline Completed")
            return preprocessor

        except Exception as e:
            logging.info("Error in Data Trnasformation")
            raise CustomException(e, sys)

    def initiate_data_transformation(self, train_path, test_path):
        try:
            # Reading train and test data
            train_df = pd.read_csv(train_path)
            test_df = pd.read_csv(test_path)

            logging.info("Read train and test data completed")
            logging.info(f"Train Dataframe Head : \n{train_df.head().to_string()}")
            logging.info(f"Test Dataframe Head  : \n{test_df.head().to_string()}")

            logging.info("Obtaining preprocessing object")

            preprocessing_obj = self.get_data_transformation_object()

            target_column_name = "Delay"
            drop_columns = target_column_name

            target_feature_train_df = train_df[[target_column_name]]
            input_feature_train_df = train_df.drop(columns=drop_columns, axis=1)

            target_feature_test_df = test_df[[target_column_name]]
            input_feature_test_df = test_df.drop(columns=drop_columns, axis=1)
            logging.info("Splitting train,test dataframes")
            ## Trnasformating using preprocessor obj.
            input_feature_train_arr = preprocessing_obj.fit_transform(
                input_feature_train_df
            )
            input_feature_test_arr = preprocessing_obj.transform(input_feature_test_df)

            logging.info(
                "Applying preprocessing object on training and testing datasets."
            )

            train_arr = np.c_[
                input_feature_train_arr, np.array(target_feature_train_df)
            ]
            test_arr = np.c_[input_feature_test_arr, np.array(target_feature_test_df)]

            save_function(
                file_path=self.data_transformation_config.preprocessor_obj_file_path,
                obj=preprocessing_obj,
            )
            logging.info("Preprocessor pickle file saved")

            return (
                train_arr,
                test_arr,
                self.data_transformation_config.preprocessor_obj_file_path,
            )

        except Exception as e:
            logging.info("Exception occured in the initiate_datatransformation")

            raise CustomException(e, sys)
